# Generated by Django 6.1 on 2026-08-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="banner_area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="banner_images/")),
                ("Discount_Deal", models.CharField(max_length=100)),
                ("Quote", models.CharField(max_length=100)),
                ("Discount", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="slider",
            name="Image",
            field=models.ImageField(upload_to="slider_images/"),
        ),
    ]
