# Generated by Django 6.1 on 2026-08-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_banner_area_alter_slider_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
