# Generated by Django 6.1 on 2026-08-21 23:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_section_alter_sub_categories_category_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Description",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="Product_Information",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
